# Generated by Django 3.1.2 on 2020-10-10 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default=datetime.datetime(2020, 10, 10, 9, 1, 35, 788091, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
    ]
