# Generated by Django 3.1.2 on 2020-10-10 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
