# Generated by Django 3.1.2 on 2020-10-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='category',
        ),
    ]
