# Generated by Django 3.1.2 on 2020-10-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20201010_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='my_image',
            new_name='image',
        ),
    ]
